# Generated by Django 5.1.2 on 2024-11-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('dailyRoutine', models.TextField(blank=True)),
                ('priorities', models.TextField(blank=True)),
                ('wakeUpTime', models.TimeField(blank=True, null=True)),
                ('bedTime', models.TimeField(blank=True, null=True)),
                ('homeSpaceUse', models.TextField(blank=True)),
                ('biggestStressors', models.TextField(blank=True)),
                ('worstHabit', models.TextField(blank=True)),
                ('dealBreakers', models.TextField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Any', 'Any')], max_length=100)),
                ('yourgender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('neatnessPreference', models.CharField(blank=True, choices=[('Very Neat', 'Very Neat'), ('Neat', 'Neat'), ('Somewhat Neat', 'Somewhat Neat'), ('Messy', 'Messy')], max_length=100)),
                ('overnightGuests', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Sometimes', 'Sometimes')], default='No', max_length=100)),
                ('pets', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=100)),
                ('confrontationStyle', models.CharField(blank=True, max_length=100)),
                ('sundayNightActivity', models.TextField(blank=True)),
                ('roommateSelfAssessment', models.TextField(blank=True)),
                ('moveInDate', models.DateField(blank=True, null=True)),
                ('moveOutDate', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('images', models.JSONField(blank=True, default=list)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SwipeActionmo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swiped_by_email', models.EmailField(max_length=254)),
                ('swiped_user_email', models.EmailField(default='default@example.com', max_length=254)),
                ('decision', models.CharField(max_length=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('swiped_by_email', 'swiped_user_email')},
            },
        ),
    ]
