# Generated by Django 5.1.2 on 2024-11-04 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwipeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swiped_yes_emails', models.JSONField(blank=True, default=list)),
                ('swiped_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swipe_action', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('swiped_by',)},
            },
        ),
        migrations.DeleteModel(
            name='SwipeActionmo',
        ),
    ]
